version: "3"
services:

  zabbix-mysql:
    container_name: zabbix-mysql
    image: mysql:latest
    networks:
      - zabbix
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:latest
    networks:
      - zabbix
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
  
  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
      - "10080:80"
    network:
      - zabbix
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix

networks:
  zabbix:
