version: "2"
services:

  zabbix-mysql:
    container_name: zabbix-mysql
    image: mysql:latest
    restart: always
    networks:
      - zabbix
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:latest
    restart: always
    ports:
    - "10051:10051"
    networks:
      - zabbix
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
  
  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:latest
    restart: always
    ports:
      - "11080:8080"
    networks:
      - zabbix
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:latest
    restart: always
    privileged: true
    ports:
    - "10050:10050"
    networks:
      - zabbix
    environment:
      - ZBX_HOSTNAME=Zabbix_host
      - ZBX_SERVER_HOST=zabbix-server

networks:
  zabbix:
